### ISSUE TITLE
[Android, Threads] Push notifications

### ISSUE THREAD

**Issue by Monks2** [vbresults/mobile-apps-for-xenforo#1]
When clicked on do not take me to the thread referenced.

**Comment by vbresults** [comment]
How consistently does this happen, and is it the same with all alert types, or is it just threads?

**Comment by Monks2** [comment]
Looks like 100% of the time for all alert types.

**Comment by vbresults** [comment]
I just put a watch on the messages so we can find out if this problem is with the add-on or the push server; generate an alert and we'll see it

**Comment by vbresults** [comment]
Ok, an alert came through; does this redirect issue happen if the app wasn't open at the time, or when the app is already open being used?

**Comment by Monks2** [comment]
Both.

**Comment by vbresults** [comment]
Fixed in 1.1.31
