### ISSUE TITLE
Push alert not working on Android 4.1.2

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#12]
S3 Mini phone, not receiving push alerts.

**Comment by vbresults** [comment]
Send another PM to testuser123 please

**Comment by RoldanLT** [comment]
Sent.

**Comment by vbresults** [comment]
If you delete app data and then log in, does it fix the issue?

**Comment by RoldanLT** [comment]
Just tried, deleting all app data/cache > re login > still not receiving push alert.
User ID tried is #5.

**Comment by vbresults** [comment]
Just found something, it's on the intermediary push server so there's nothing to do on your end -- try sending a pm to testuser123 again, I'll send you one too

**Comment by vbresults** [comment]
Just sent you a PM

**Comment by vbresults** [comment]
Try liking of one test account's PM's

**Comment by vbresults** [comment]
Fixed!  Clear app data and log in, and it will register your new token.  Thank you for all of the help in tracking this down (:

**Comment by RoldanLT** [comment]
Some error log after update:

Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: Unknown Account, 17 minutes ago
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(25): MobileInterface_PushAlert_Transport::send('messages', Array)
#2 /public/library/MobileInterface/Listener.php(46): MobileInterface_PushAlert_Transport::messages(Array)
#3 [internal function]: MobileInterface_Listener::pushAlertQueueSend(Array)
#4 /public/library/XenForo/Model/Cron.php(357): call_user_func(Array, Array)
#5 /public/library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#6 /public/library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 7.9999990463257, '')
#7 /public/library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 7.9999990463257, '', false)
#8 /public/library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, NULL, '', false)
#9 /public/deferred.php(23): XenForo_Model_Deferred->run(false)
#10 {main}
Request State
array(3) {
  ["url"] => string(37) "/deferred.php"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(3) {
    ["_xfRequestUri"] => string(53) "/f/smart-talk-n-text-sun.135/page-25?order=view_count"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}



Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: vinzoimartinez, 48 minutes ago
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#2 /public/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Milano_LiveFeed_ControllerPublic_Account))
#3 /public/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#4 /public/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /public/index.php(13): XenForo_FrontController->run()
#6 {main}
Request State
array(3) {
  ["url"] => string(61) "/index.php?account/push-alert-register"
  ["_GET"] => array(1) {
    ["account/push-alert-register"] => string(0) ""
  }
  ["_POST"] => array(4) {
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
    ["platform"] => string(7) "android"
    ["token"] => string(152) "fxx-0NwConk:APA91bGQHUWmuSn8OJhrash0B1lHuI0aa_MSZV-_6JOn7gK5bjzY3p58bKOARrCl66M4wTu4DCd_KutqTsZWhcR7XK5KOAfM1WlArQyGr6yt5NPETcqcKtp72EJjb0noq6RyrwQDJrcM"
  }
}




Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: Unknown Account, Today at 11:02 AM
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(25): MobileInterface_PushAlert_Transport::send('messages', Array)
#2 /public/library/MobileInterface/Listener.php(46): MobileInterface_PushAlert_Transport::messages(Array)
#3 [internal function]: MobileInterface_Listener::pushAlertQueueSend(Array)
#4 /public/library/XenForo/Model/Cron.php(357): call_user_func(Array, Array)
#5 /public/library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#6 /public/library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 7.9999978542328, '')
#7 /public/library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 7.9999978542328, '', false)
#8 /public/library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, NULL, '', false)
#9 /public/deferred.php(23): XenForo_Model_Deferred->run(false)
#10 {main}
Request State
array(3) {
  ["url"] => string(36) "/deferred.php"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(3) {
    ["_xfRequestUri"] => string(1) "/"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}

**Comment by RoldanLT** [comment]
Another error:

Server Error Log
Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: cyverboy1993, Today at 1:06 PM
Stack Trace
#0 /home/nginx/domains/phcorner.net/public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#2 /public/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Milano_LiveFeed_ControllerPublic_Account))
#3 /public/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#4 /public/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /public/index.php(13): XenForo_FrontController->run()
#6 {main}
Request State
array(3) {
  ["url"] => string(61) "/index.php?account/push-alert-register"
  ["_GET"] => array(1) {
    ["account/push-alert-register"] => string(0) ""
  }
  ["_POST"] => array(4) {
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
    ["platform"] => string(7) "android"
    ["token"] => string(152) "fF2NgBuHq8M:APA91bFaE678e3QuFM92Irpsxn87hq543vsITwX3H4ugSBFgdwXTGbIFe6v6cn0xIdFxYfYHDvJq0BSTJa_DCxNhY2eHS4iyF5jSdxa_aSmuSEC_c06bTnfwjE9KCfjOJk8_8h39J6er"
  }
}

**Comment by vbresults** [comment]
Please open a separate issue for this -- on topic, are you receiving alerts again?

**Comment by RoldanLT** [comment]
About alerts, still nothing.
I will try to clear app data again if you want.

**Comment by RoldanLT** [comment]
Just tried again, clearing app data cache.
Still no push alert for me.
I have a PM on the site for you also.
Thanks!

**Comment by RoldanLT** [comment]
Just an update. Push alert now works on my phone.
