### ISSUE TITLE
What PHP version/specific modules does your app requires by the way?  

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#13]
I'm using PHP 5.6.15 by the way.

With this module:
# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
ereg
exif
filter
gd
gettext
gmp
hash
iconv
imagick
imap
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by vbresults** [comment]
It has no special requirements above what XenForo requires, it was made this way by design for compatibility with a wide number of installs.  The add-on is pretty light anyway (:
