### ISSUE TITLE
Server Error Logs

### ISSUE THREAD

**Issue by tosalem** [vbresults/mobile-apps-for-xenforo#14]
Hello
After the last update these mistakes appeared. See Attachments
Note that  alerts appeared  only once and stopped
![server error logs1](https://cloud.githubusercontent.com/assets/15699587/11169257/955adf04-8bc3-11e5-8247-e27d1a627845.jpg)

![server error logs2](https://cloud.githubusercontent.com/assets/15699587/11169262/a9188690-8bc3-11e5-9730-9e7cc2fbd820.jpg)

**Comment by vbresults** [comment]
Fixed in 1.1.32
