### ISSUE TITLE
[ERROR] Error initializing Cordova: Class not found

### ISSUE THREAD

**Issue by tosalem** [vbresults/mobile-apps-for-xenforo#16]
Error intilaizing
Cordova: class not found

![error intilaizing](https://cloud.githubusercontent.com/assets/15699587/11189193/ea3094ec-8c9f-11e5-8332-7585bc5150f5.JPG)

![error intilaizing1](https://cloud.githubusercontent.com/assets/15699587/11189200/efd8782e-8c9f-11e5-8754-fda1911a771f.JPG)

**Comment by vbresults** [comment]
Does this happen every time?  Are you logged in every time this happens?

**Comment by tosalem** [comment]
Yes, this happens all the time
Yes it happens with the login and without login
 and also occurs during movement at the site every time Open Link
========
Another problem has got me earlier while browsing the site and then stopped (the default browser)
  But still spoke with my friends see photos attached
I had to arrest added at this time
![1](https://cloud.githubusercontent.com/assets/15699587/11198350/3c8c15ec-8cd5-11e5-824a-548cb76568f5.png)

![2](https://cloud.githubusercontent.com/assets/15699587/11198360/47e4bd04-8cd5-11e5-8805-64069ae8078b.png)

![3](https://cloud.githubusercontent.com/assets/15699587/11198364/4e8699a2-8cd5-11e5-97bf-c2b80a29f848.png)

**Comment by tosalem** [comment]
ملاحظة: بعد تعطيل الاضافة توقفت المشاكل الآن

**Comment by vbresults** [comment]
Enable add-on but clear browser cache and let me know if that fixes it

**Comment by vbresults** [comment]
As for the app error, clear app data and let me know if it's fixed

But the app error should only happen if the app is out of date

**Comment by tosalem** [comment]
I did that and still show the same problem

**Comment by vbresults** [comment]
Ok, leave add-on enabled and I will visit your site then tell you when I'm finished

**Comment by tosalem** [comment]
ok

**Comment by vbresults** [comment]
Does the issue happen only when logged in or also as a guest?  Please make me a test account

**Comment by tosalem** [comment]
all
when logged  and a guest
 
user name
test account
 pass
test123
Date: Mon, 16 Nov 2015 20:21:05 -0800

**Comment by vbresults** [comment]
I can't reproduce the errors in the browser as a guest -- can you confirm?

**Comment by tosalem** [comment]
see 
when logged and a guest
same problem

![alert](https://cloud.githubusercontent.com/assets/15699587/11202856/dac58518-8cfd-11e5-809e-1999a986d8ae.png)


![alert1](https://cloud.githubusercontent.com/assets/15699587/11202859/e624e458-8cfd-11e5-88ea-75c67173e7f6.png)

**Comment by vbresults** [comment]
Just sent you an XML by email to upgrade the add-on; install it and let me know if the popup still happens for guests in the default browser

**Comment by tosalem** [comment]
OK now I got no problem with me about the guest in the default browser As well as the application but it became very slow And returned problem after login

**Comment by vbresults** [comment]
What problem?

**Comment by tosalem** [comment]
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/15699587/11204121/b64cfb26-8d0c-11e5-83d6-758dbc80b5a1.png)

**Comment by vbresults** [comment]
This is in the app?

**Comment by tosalem** [comment]
yes

**Comment by vbresults** [comment]
Are you having any problems in the default browser as a logged in user?  Just want to confirm, before we move onto the app

**Comment by tosalem** [comment]
no problem for guests in the default browser now and when logged  is good
and 
no problem for guests in the app now but very slow

now only problem when logged

**Comment by vbresults** [comment]
What android version and device?

**Comment by tosalem** [comment]
![image](https://cloud.githubusercontent.com/assets/15699587/11235112/96d56f66-8ddf-11e5-8f2d-959855c99e2c.jpeg)
![image](https://cloud.githubusercontent.com/assets/15699587/11235113/96d70678-8ddf-11e5-990f-7a142fc87ac7.jpeg)
![image](https://cloud.githubusercontent.com/assets/15699587/11235114/96d87472-8ddf-11e5-8e49-7f4659d23f0c.jpeg)

**Comment by vbresults** [comment]
It's possible something went wrong when we updated your android app, will check on the next update on Tuesday

**Comment by vbresults** [comment]
Fixed "[ERROR] Error initializing Cordova: Class not found." problem on Android. If you are running 1.1.32 of the add-on or higher, this fix takes effect immediately.
