### ISSUE TITLE
How can I put back the navigation menu on top?

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#2]
As I can see on your screenshots, Main navigation menu is on the bottom of the page now.
I don't like it, and I want the default xenforo behavior.
How can I do that?
Thanks a lot!

**Comment by vbresults** [comment]
You are talking about the enhanced style; this view is only available when the default "Release" setting is changed from "Stable" to "Latest".  Revert back to "Stable" and the default responsive style will show.
