### ISSUE TITLE
Can you please only load your libraries on mobile visitor and not for Desktop users?

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#22]
I mean this: //cdn.vbresults.com/libraries/??smart-app-banner/.....

**Comment by RoldanLT** [comment]
I want to save some files to load, and remove those un-necessary.

**Comment by vbresults** [comment]
In the case of desktop visitors, this is also necessary -- it is loaded for the smart banner/install prompt which desktop visitors need to know about the app, both members and guests visiting for the first time.
