### ISSUE TITLE
First link click

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#23]
Everytime I open the iPhone app, the first link that I click seems to be lagging.

After the first link click, the rest of the link clicks seems to work fine.

**Comment by vbresults** [comment]
Should be fixed in 1.1.38, will have to wait for the admin to install the add-on update for the respective forum.

**Comment by bloh2** [comment]
Doesn't seem to fix it.

**Comment by vbresults** [comment]
See #20
