### ISSUE TITLE
Problem with external links, direct download links not working

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#25]
Someone reported this issue here: 
http://phc.onl/t/111817/

**Comment by vbresults** [comment]
Please ask them if it's fixed now.

**Comment by RoldanLT** [comment]
Thanks!

**Comment by RoldanLT** [comment]
User said, still not working :|.

**Comment by vbresults** [comment]
Get more info from them -- app platform, app version, os version

**Comment by RoldanLT** [comment]
Of course it is Android platform and Latest version.

**Comment by vbresults** [comment]
Fixed in the upcoming version 1.1.41 of the Android and iOS apps.
