### ISSUE TITLE
Don't show blank page on every link click

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#26]
For your app, whenever I clicked a link, it will then show blank page & when the loading is nearly done, it will then show the webpage. 

Can it be done similar to safari browser? For safari browser, whenever I clicked a link, it will remain at the same page first with the loading bar start moving. When the page is halfway done, it will then straight away show the new page without showing any blank page.

**Comment by bloh2** [comment]
One of the reason is that I have a sticky header & I don't want it to disappear on every link click.

**Comment by vbresults** [comment]
Due to technical reasons we cannot implement this at this time.  If anything changes, will update the ticket.

**Comment by vbresults** [comment]
This should have been fixed with the upgrade in app engines a few weeks ago (:
