### ISSUE TITLE
Android 4.2.2 App Crash/Hang Problem

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#28]
Reported from one user here: http://phc.onl/t/113756/

Example scenario:
User browsing a long thread, scrolling down and reading and then app just freeze and makes the phone not usable.
So he was force to remove the battery to boot up the phone.

**Comment by vbresults** [comment]
I think the phone is running out of memory when this happens.  Can they reproduce this with the browser?

**Comment by RoldanLT** [comment]
They can't re-produce this on browser.

**Comment by vbresults** [comment]
There are certain resource limitations inside apps that the browsers don't have and until we can find a solution to this we'll leave the ticket open

**Comment by vbresults** [comment]
This was automatically fixed when we upgraded the Android engine a few weeks ago (:
