### ISSUE TITLE
Swipe to go back not working well

### ISSUE THREAD

**Issue by reddyinc** [vbresults/mobile-apps-for-xenforo#29]
Can we bring back back arrow for navigation? Or have both?
swipe to back is not working.. Significant delays which makes it apprear like app is broken.

**Comment by vbresults** [comment]
We are required to add navigation arrows to iOS again in the next update for unrelated reasons, so you can consider this fixed.

**Comment by vbresults** [comment]
In response to your direct query, this is part of .41.  It was not included in the recent list of instant fixes.

**Comment by vbresults** [comment]
Update: We'll be fixing the swipe navigation so it can no longer be triggered accidentally, and fixing the direction of the swipe as well, instead of implementing arrow navigation.
