### ISSUE TITLE
App Banner for Android

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#35]
For IOS, the app banner (not sticky / not fixed) works fine with my sticky navigation. (see photo)

But for android, the app banner (sticky / fixed) is not working well. (see photo)

---------

**IOS** (Ok - with non-sticky app banner)

When first loaded:
![ios1](https://cloud.githubusercontent.com/assets/11502455/13178846/07aa2752-d75c-11e5-8346-1587249bee06.png)

When scroll down:
![ios2](https://cloud.githubusercontent.com/assets/11502455/13178849/08f572ba-d75c-11e5-87a8-927e002503cd.png)

When scroll down further:
![ios3](https://cloud.githubusercontent.com/assets/11502455/13178843/0796f236-d75c-11e5-9a35-c9651918260c.png)

**Android** (Not Ok - with sticky app banner)

When first loaded:
![android1](https://cloud.githubusercontent.com/assets/11502455/13178844/079c8f7a-d75c-11e5-833c-ed0390b53503.png)

When scroll down:
![android2](https://cloud.githubusercontent.com/assets/11502455/13178845/07a39414-d75c-11e5-8bac-5acf96e99937.png)

**Comment by vbresults** [comment]
The app banner is meant to be sticky; this is not a bug.  The reason it looks the way it does iOS is because it's actually not using our smart banner code, it's using the built-in iOS smart banner system.

**Comment by bloh2** [comment]
What about loading the banner before my fixed navigation become sticky?
Cause right now when I first loaded a page, my sticky navigation will stay at top with the banner & leave lots of whitespace at bottom:

![image](https://cloud.githubusercontent.com/assets/11502455/13373211/ff717eaa-dd9b-11e5-8295-764f07d0622f.png)

**Comment by bloh2** [comment]
And is it possible to add extra CSS to the app banner? If yes, how do I inspect the elements?

**Comment by vbresults** [comment]
It's not; in 2.0 the CSS for the app banner will be bundled with the XenForo add-on and you'll be able to change it there.
