### ISSUE TITLE
Icon incorrect

### ISSUE THREAD

**Issue by Dannymh** [vbresults/mobile-apps-for-xenforo#37]
The app icon I submitted is not correct. I submitted a correctly formatted icon with a white background, however on iOS the icon has a black background, which doesnt look right and is against our colour scheme.

How do we go about getting this correct, i.e. being our logo with the white background as submitted.

This seemed/was correc ton the android one when I last checked but I do not have access to an android device ATM to double check

**Comment by Dannymh** [comment]
this is for silvertails.net account

**Comment by vbresults** [comment]
We don't add transparency to the logos so my guess is that the photo had an alpha channel even though you may not have been aware of it.  Google and Apple may handle this differently.

Email a 1024^2 PNG logo to updates+pma and we'll include it in the next batch of iOS updates (note: at the mininum will be a few weeks).
