### ISSUE TITLE
Swipe back on iOS too sensitive

### ISSUE THREAD

**Issue by Dannymh** [vbresults/mobile-apps-for-xenforo#38]
Hi,

On the iOS device I am finding the swipe go back is a little too sensitive, it seems to randomly go back when I am scrolling up or down within the forum.

Is there anyway to adjust the sensitivity of this feature or to perhaps link it to a different gesture?

**Comment by bloh2** [comment]
A back drag similar to iOS safari would be best.

**Comment by vbresults** [comment]
Duplicate of #29 .
