### ISSUE TITLE
Attachment Download Not working?

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#4]
One IOS app user on my forum reported that he can't download .rar attachment.

**Comment by vbresults** [comment]
What happens when they click the link?

**Comment by RoldanLT** [comment]
Just nothing happens when they tap the attachment link.

**Comment by vbresults** [comment]
How do we reach this on the app

**Comment by RoldanLT** [comment]
Do you mean how to re-produce?
We have this thread/topic with .rar file attached, when an IOS user try to download the file just nothing happens.

Or do you mean something?

**Comment by vbresults** [comment]
Yes, what thread

**Comment by RoldanLT** [comment]
I'm asking the user now who reported.

**Comment by vbresults** [comment]
This issue has been confirmed, duplicate of #6.
