### ISSUE TITLE
Admin Option cannot be opened (ErrorException: Fatal Error: Call to undefined method MobileInterface_Helper_Template::phraseText)

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#40]
1.1.40.1 addon :

The admin option can't be opened after upgrading.

ErrorException: Fatal Error: Call to undefined method MobileInterface_Helper_Template::phraseText() -library/MobileInterface/Option/StyleChooser.php:18
Generated By: xxx, 1 minute ago

**Comment by vbresults** [comment]
Re-download the zip and re-do the upgrade -- there was a problem in the previous zip.
