### ISSUE TITLE
Push notification message for conversation

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#41]
I personally dislike the push notification message for conversation (didn't mention the user who reply the conversation) & wish to customize the message. If you could provide phrase with variable: {sender name}, {conversation title}, {conversation message}, that would be great.

I've got no issue with push notification message for alerts, only for conversation.

**Comment by vbresults** [comment]
It should be showing the last person who replied, if it isn't, who is it showing?

**Comment by bloh2** [comment]
Currently:
{Conversation Title} - New reply to your conversation

I was hoping for:
{Sender Name} replied to your conversation "{Conversation Title}"

**Comment by vbresults** [comment]
This works off the phrase system, and uses the XenForo email subject phrases, so if you edit the "conversation_reply_email_subject" you can get the result you're after.

The variable for the username is {username} that said, it will affect your email notification subject lines too, and if you are ok with that, then you can change that to the exactly what you want.
