### ISSUE TITLE
Server Errors if users go to missing routes

### ISSUE THREAD

**Issue by Dannymh** [vbresults/mobile-apps-for-xenforo#42]
If users on the forum not within the app go to an invalid URL the mobileinterface plugin is generating errors

"ErrorException: Undefined index: HTTP_USER_AGENT - library/MobileInterface/Listener.php:40"

`-- stack trace redacted for security --`

The `redacted` is not a location on my system so unsure where it is pulling that from

**Comment by vbresults** [comment]
This is fixed in 1.1.40.2, to be released soon;

The path you provided is the absolute location on your server; your FTP server may be configured to have public_html as the root for your FTP user though, so it appears to you as "/" in your FTP client.
