### ISSUE TITLE
Push Notifications not work

### ISSUE THREAD

**Issue by tosalem** [vbresults/mobile-apps-for-xenforo#5]
Hello
Push notifications does not work with me and also attached pdf file Broken think because of the possibility to open a new page
And also video Media Gallery does not function well vimeo only sound works without a photo, for example,
But YouTube does not function until the normal situation is pressed to enlarge the screen thereby acting
I hope that you replace these observations, especially notifications

Thank you

salem 
https://play.google.com/store/apps/details?id=com.q8ow.app

**Comment by vbresults** [comment]
Make sure your configuration correct, we see no problems with push alerts on our side of the system; email a screenshot of your configuration to us and we'll tell you what we see

**Comment by tosalem** [comment]
Thank you for your interest

**Comment by vbresults** [comment]
The problem with the alerts has been found, will be resolved within 72 hours

**Comment by vbresults** [comment]
Fixed in 1.1.31; note that you will have to wait for the app update and then update your app
