### ISSUE TITLE
xen:description for IOS native title

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#51]
## 2. Are you requesting a new feature?
- Yes

### 2.1. If so, delete everything above #2, and describe your idea
- For IOS native title bar, can you add second row for xen:description?
- By second row, I mean similar to whatsapp "last seen today xxxx".

![image](https://cloud.githubusercontent.com/assets/11502455/13603521/c8d92df4-e578-11e5-8b77-894aca513dde.png)

**Comment by vbresults** [comment]
See #52

**Comment by bloh2** [comment]
I thought this shouldn't be considered as customization. Isn't it a standard feature to have second row?

**Comment by bloh2** [comment]
So, you're not going to include this feature into the general release?

**Comment by vbresults** [comment]
@bloh2 Not at this time.  When the spring season of the development cycle comes we'll re-evaluate closed enhancement requests and re-open some to feedback.

**Comment by bloh2** [comment]
Too bad. :(
This second row feature shouldn't be too hard to add it.
