### ISSUE TITLE
IOS native title bar

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#52]
## 2. Are you requesting a new feature?
Yes

### 2.1. If so, delete everything above #2, and describe your idea
- Can there be an on/off button for having the IOS native title bar? Cause it might not fit well with fixed navigation.

**Comment by vbresults** [comment]
The primary purpose of the navigation bar in iOS was to add the back button; without this the app will return to swipe navigation which many people complained about.

If you want your app specifically tailored with a custom feature like this, stay tuned, as we'll be adding a customization service in the future.
