### ISSUE TITLE
Android Native Title Bar? If not, different custom style for Android & IOS.

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#53]
## 2. Are you requesting a new feature?
Yes

### 2.1. If so, delete everything above #2, and describe your idea
- Will Android get native title bar similar to IOS? If not, it's better to let us choose different custom style for Android & IOS separately. Meaning Android & IOS will each get assigned to a different style. Right now, you can only choose 1 style for both IOS & Android.

**Comment by vbresults** [comment]
Android will get a native title bar similar to iOS, likely at the end of the month or the beginning of the next one (:
