### ISSUE TITLE
A small part of the bottom part of the website is hidden  (might due to the IOS native title bar)

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#55]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
A small part of the bottom part of the website is hidden. (might due to the IOS native title bar)

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.1.41) - Newest
- Platform (choose): XenForo
- Add-on Version: (1.1.40.1)
- XenForo Version: (1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
Just load any webpage using the app.

### 1.5. Is there an error message involved?  If so, please paste
Nope.

**Comment by vbresults** [comment]
This is fixed in 1.1.42 (:
