### ISSUE TITLE
Slow native title bar update

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#56]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
After page load, the native title bar will only update after 2 seconds later.
It should updates together with the page load.

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.1.41)
- Platform (choose): XenForo
- Add-on Version: (1.1.40)
- XenForo Version: (1.5.5)

**Comment by vbresults** [comment]
This is fixed in the upcoming 1.2.0 release (:
