### ISSUE TITLE
Ajax loading icon 

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#57]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
For IOS, when a user is logged in, for every page load, the Ajax loading bar will appear for a short while. This didn't happen in native browser and Android as well. Only in IOS app.

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.1.41)
- Platform (choose): XenForo
- Add-on Version: (1.1.40)
- XenForo Version: (1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
Just load any page when user is logged in.

### 1.5. Is there an error message involved?  If so, please paste
Nope.

**Comment by vbresults** [comment]
This is due to the iOS app not supporting fixed CSS positions; it will be rectified when we can get an upstream fix.

**Comment by bloh2** [comment]
Change the style to default style & disable all the addons, except yours. The ajax icon still loads on the starting of every pages.

**Comment by vbresults** [comment]
When we say upstream, this referring to the developers of our various tools we use in coding the apps.  I am not referring to add-on developers -- this is not a problem on your forum at all.

Fixed CSS positions are not stable in iOS, this we know for certain.
