### ISSUE TITLE
IOS back button

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#58]
1. The back button should be hidden if back is not available. Meaning the first loading page shouldn't have back button.

2. The back button arrow "<" should have the same design as the default IOS "<" icon.

Just an additional question:
1. Can I hide the back button using CSS?

**Comment by vbresults** [comment]
#1 and #2 are implemented in 1.2.0; thank you for bringing this to the front of my mind (:

It is not possible to hide the back button using CSS; the menu is 100% native iOS code.
