### ISSUE TITLE
Native title bar Overflow

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#59]
When the title bar overflow, it should just squeeze the title or break it into 2 lines to fit all the words in the title bar.

Right now, it just show "....." for overflow.

**Comment by vbresults** [comment]
The solution we've made in 1.2.0 is to cut off the title tag suffix so the ... happens more rarely -- so instead of `This is a thread title | Your Forum Name` the bar reads `This is a thread title`.
