### ISSUE TITLE
Color of the app title bar and status bar

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#61]
The color of the app title bar and status bar will change immediately when we set it in the XF style property? Even though we didn't set it in your app page?

Cause you mention this: " if your colors aren't set by then you'll have to wait until the next update, or set the colors inside your style properties (xf) or stylevars (vb). "

By the way, for the status bar, if I want text color white with transparent background, similar to your screenshot, what is the theme that I should select? Light one?

**Comment by vbresults** [comment]
Yes, the color of the app title bar and status bar will change on the next page load when you set it in the XF style property, even though you didn't set it in your app page.

Yes, the "light" does exactly that -- it creates white text on a transparent background.  "dark" is black text on a transparent background.
