### ISSUE TITLE
Progress indicator & error handling

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#62]
[What's on the Roadmap]

**- A very visible progress indicator so link clicks/page transitions don't feel laggy.**
**- More intuitive error handling system for when the network is down or there's a problem at the forum side.**

May I know how are those going?

**Comment by vbresults** [comment]
The faster titlebar update provides a faster response to link clicks/page transitions

**Comment by bloh2** [comment]
1. The problem is that those with slow internet connectivity will not get any response from you until the new page is loaded. This will cause them to click the link over & over again, which causes the link to load/refresh over & over again, which in the end the link didn't manage to finish loading in the desired period.

2. What about the error handling when there is no internet connection?

**Comment by vbresults** [comment]
A progress indicator has been added in 1.2.5 (:
