### ISSUE TITLE
App causing errors for users using mobile browsers

### ISSUE THREAD

**Issue by Monks2** [vbresults/mobile-apps-for-xenforo#9]
had to disable

![mms95img371105153](https://cloud.githubusercontent.com/assets/15717185/11157448/6c5000b2-8a1f-11e5-9467-12d4a1e54b3d.jpg)
![mms95img1987945832](https://cloud.githubusercontent.com/assets/15717185/11157447/6c4e0046-8a1f-11e5-8e74-069cc516ebdd.jpg)

**Comment by Monks2** [comment]
![err2](https://cloud.githubusercontent.com/assets/15717185/11161669/2cffad68-8a51-11e5-96cb-1ebffafc30a6.jpg)

**Comment by Monks2** [comment]
![2err](https://cloud.githubusercontent.com/assets/15717185/11161674/54904536-8a51-11e5-9402-4281a1ef8c3c.jpg)

**Comment by vbresults** [comment]
Fixed

**Comment by Monks2** [comment]
This is still happening. Cache cleared

**Comment by Monks2** [comment]
three popup dialogs
gap_init:2
gap:[null,"NetworkStatus","getConnectionInfo","NetworkStatus1249584673"]
gap:[null,"App","show","App489127131"]

**Comment by vbresults** [comment]
Just realized these were coming from prompts instead of alerts, it's been fixed, thank you for reporting again
